### ISSUE TITLE
Support ASP.NET 5 RC1

### ISSUE THREAD

**Issue by Xacron** [Xacron/oauth-aspnet#10]
Dev and master branches will be updated to support ASP.NET 5 RC1 while it is unreleased.

**Comment by Xacron** [comment]
https://github.com/XacronDevelopment/oauth-aspnet/commit/bbfc6be7f707a89e17c8a3ae95db84f6b2b3e15d

**Comment by pbarrios** [comment]
Are you working in the version of AspNet5 1.0.0-rc1-final?

**Comment by Xacron** [comment]
Yes I am... some significant changes were made for RC1 final, so it will take me a few days after the Thanksgiving holidays to complete the updates.

On Tue, Nov 24, 2015 at 11:15 AM -0800, "Pablo" notifications@github.com wrote:

Are you working in the version of AspNet5 1.0.0-rc1-final?

---

**Comment by pbarrios** [comment]
Great! :+1:

**Comment by 717009629** [comment]
能快一点吗，急需啊

**Comment by Xacron** [comment]
> 能快一点吗，急需啊

非常忙碌的一年的时间，希望很快

**Comment by Xacron** [comment]
Back from a very long winter vacation; The Dev branch code has been updated to a running state for RC1. A couple more minor changes remaining for RC1. NuGet packages for RC1 support coming in the next day or so.

**Comment by Xacron** [comment]
NuGet packages updated with ASP.NET RC1-Update1 support
